### ISSUE TITLE
Package fails to build with cargo 1.75

### ISSUE THREAD

**Issue by eddelbuettel** [alexhroom/rshift#32]
Congratulations on getting a new version to CRAN.

Now. the Ubuntu LTS releases only have rustc and cargo up to version 1.75.  The build then fails as follows:

```r
Using cargo 1.75.0
Using rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball)
Building for CRAN.
Cleaning previous `src/Makevars`.
Writing `src/Makevars`.
`tools/config.R` has finished.
** libs
using C compiler: ‘gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0’
# Check if NOT_CRAN is false and unzip vendor.tar.xz if so
if [ "" != "true" ]; then \
        if [ -f ./rust/vendor.tar.xz ]; then \
                tar xf rust/vendor.tar.xz && \
                mkdir -p /mnt/build/noble/rshift/src/rshift/src/.cargo && \
                cp rust/vendor-config.toml /mnt/build/noble/rshift/src/rshift/src/.cargo/config.toml; \
        fi; \
fi
export CARGO_HOME=/mnt/build/noble/rshift/src/rshift/src/.cargo && \
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin" && \
RUSTFLAGS=" --print=native-static-libs" cargo build -j 2 --offline --lib --release --manifest-path=./rust/Cargo.toml --target-dir ./rust/target
error: failed to parse lock file at: /mnt/build/noble/rshift/src/rshift/src/rust/Cargo.lock

Caused by:
  lock file version 4 requires `-Znext-lockfile-bump`
make: *** [Makevars:28: rust/target/release/librshift.a] Error 101
ERROR: compilation failed for package ‘rshift’
```

The use of 'lock file version 4' implies 1.78 which is not availble.  I have been told [last week](https://github.com/extendr/b64/issues/8#issuecomment-2769778945) by @josiahparry that you can circumvent this by setting `rust_version = "1.65.0"` in you `Cargo.toml` to not rely on newer features such as lockfile version 4.

This would allow wider distribution of your package so maybe this is something to consider for the next upload.

**Comment by JosiahParry** [comment]
Thanks, Dirk! @CGMossa and I are hashing out the final bits of a new extendr release and will have some notes for this. You'll be a rust developer on accident soon enough lol!
