### ISSUE TITLE
Installation fails on Linux (Cargo.lock version 4 requires -Znext-lockfile-bump)

### ISSUE THREAD

**Issue by DarshanaG29** [alexhroom/rshift#33]
Problem: Installation of rshift (v3.1.2) fails consistently on Linux when building the Rust component.
Exact Error: lock file version 4 requires \-Znext-lockfile-bump``
Environment:
-     OS: Linux (x86_64-pc-linux-gnu)
-     R Version: 4.5.1
-     Rust/Cargo Version: 1.75.0

Attempts Made: CRAN install, R-Universe install, GitHub install (all failed with the same error).

install.packages("remotes")
remotes::install_github("alexhroom/rshift")

And the error shown was:
error: failed to parse lock file at: /tmp/Rtmp9Q6Epi/R.INSTALL166ce623cbf2f/rshift/src/rust/Cargo.lock
Caused by:
  lock file version 4 requires `-Znext-lockfile-bump`
make: *** [Makevars:28: rust/target/release/librshift.a] Error 101
ERROR: compilation failed for package ‘rshift’
* removing ‘/home/darshana/R/x86_64-pc-linux-gnu-library/4.5/rshift’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpuW2dfP/file1549071e165d7/rshift_3.1.2.tar.gz’ had non-zero exit status

**Comment by alexhroom** [comment]
I think this might be caused by #32 ?
